apiVersion: v1
kind: Service
metadata:
  name: key-value-thingy
  labels:
    app: key-value-thingy
spec:
  ports:
    - port: 8080
      name: key-value-thingy
  selector:
    app: key-value-thingy
  type: LoadBalancer
