apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: key-value-thingy-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: key-value-thingy
    spec:
      containers:
        - image: xcalibre/key-value-image
          name: key-value-thingy
          ports:
            - containerPort: 8080
              name: custom-port
